In [1]:
%%capture
%load_ext sql
%sql sqlite:///chinook.db

'Connected: None@chinook.db'

## Answering Business Questions Using SQL

### Investigating Tables and Views of database

Writing a query to return information on the tables and views in the database:

In [5]:
%%sql
SELECT
    name,
    type
FROM sqlite_master
WHERE type IN ("table","view");

Done.

[('album', 'table'),
 ('artist', 'table'),
 ('customer', 'table'),
 ('employee', 'table'),
 ('genre', 'table'),
 ('invoice', 'table'),
 ('invoice_line', 'table'),
 ('media_type', 'table'),
 ('playlist', 'table'),
 ('playlist_track', 'table'),
 ('track', 'table')]

Learning more about the dataset:

In [18]:
%%sql
SELECT
    media_type_id,
    name,
    CASE
        WHEN name LIKE '%Protected%' THEN 1
        ELSE 0
        END
        AS protected
FROM media_type;

Done.

[(1, 'MPEG audio file', 0),
 (2, 'Protected AAC audio file', 1),
 (3, 'Protected MPEG-4 video file', 1),
 (4, 'Purchased AAC audio file', 0),
 (5, 'AAC audio file', 0)]

In [12]:
%%sql
SELECT
    first_name,
    last_name,
    phone
FROM customer
WHERE first_name LIKE "%Jen%";

Done.

[('Jennifer', 'Peterson', '+1 (604) 688-2255')]

In [13]:
%%sql
SELECT e1.first_name || ' ' || e1.last_name employee_name, e1.title employee_title, e2.first_name || ' ' || e2.last_name supervisor_name, e2.title supervisor_title
FROM employee e1
LEFT JOIN employee e2 on e1.reports_to = e2.employee_id
ORDER BY 1;

Done.

[('Andrew Adams', 'General Manager', None, None),
 ('Jane Peacock', 'Sales Support Agent', 'Nancy Edwards', 'Sales Manager'),
 ('Laura Callahan', 'IT Staff', 'Michael Mitchell', 'IT Manager'),
 ('Margaret Park', 'Sales Support Agent', 'Nancy Edwards', 'Sales Manager'),
 ('Michael Mitchell', 'IT Manager', 'Andrew Adams', 'General Manager'),
 ('Nancy Edwards', 'Sales Manager', 'Andrew Adams', 'General Manager'),
 ('Robert King', 'IT Staff', 'Michael Mitchell', 'IT Manager'),
 ('Steve Johnson', 'Sales Support Agent', 'Nancy Edwards', 'Sales Manager')]

In [14]:
%%sql
SELECT al.title album, ar.name artist, COUNT(*) tracks_purchased FROM invoice_line il
INNER JOIN track t ON t.track_id = il.track_id
INNER JOIN album al ON al.album_id = t.album_id
INNER JOIN artist ar ON ar.artist_id = al.artist_id
GROUP BY 1
ORDER BY 3 DESC 
LIMIT 5;

Done.

[('Are You Experienced?', 'Jimi Hendrix', 187),
 ('Faceless', 'Godsmack', 96),
 ('Mezmerize', 'System Of A Down', 93),
 ('Get Born', 'JET', 90),
 ('The Doors', 'The Doors', 83)]

In [15]:
%%sql
SELECT ta.artist_name artist, COUNT(*) tracks_purchased FROM invoice_line il
INNER JOIN (SELECT t.track_id, ar.name artist_name FROM track t 
            INNER JOIN album al ON al.album_id = t.album_id 
            INNER JOIN artist ar ON ar.artist_id = al.artist_id) ta 
           ON ta.track_id = il.track_id
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 10;

Done.

[('Queen', 192),
 ('Jimi Hendrix', 187),
 ('Nirvana', 130),
 ('Red Hot Chili Peppers', 130),
 ('Pearl Jam', 129),
 ('AC/DC', 124),
 ("Guns N' Roses", 124),
 ('Foo Fighters', 121),
 ('The Rolling Stones', 117),
 ('Metallica', 106)]

In [16]:
%%sql
SELECT t.track_id, ar.name artist_name FROM track t
INNER JOIN album al ON al.album_id = t.album_id
INNER JOIN artist ar ON ar.artist_id = al.artist_id
ORDER BY 1 LIMIT 5;

Done.

[(1, 'AC/DC'), (2, 'Accept'), (3, 'Accept'), (4, 'Accept'), (5, 'Accept')]

### Selecting New Albums to Purchase

Selecting the first three albums that will be added to the store, from a list of four

Write a query that returns each genre, with the number of tracks sold in the USA:

    in absolute numbers

In [23]:
%%sql
SELECT
    DISTINCT(name),
    genre_ID
FROM genre
ORDER BY 1;

Done.

[('Alternative', 23),
 ('Alternative & Punk', 4),
 ('Blues', 6),
 ('Bossa Nova', 11),
 ('Classical', 24),
 ('Comedy', 22),
 ('Drama', 21),
 ('Easy Listening', 12),
 ('Electronica/Dance', 15),
 ('Heavy Metal', 13),
 ('Hip Hop/Rap', 17),
 ('Jazz', 2),
 ('Latin', 7),
 ('Metal', 3),
 ('Opera', 25),
 ('Pop', 9),
 ('R&B/Soul', 14),
 ('Reggae', 8),
 ('Rock', 1),
 ('Rock And Roll', 5),
 ('Sci Fi & Fantasy', 20),
 ('Science Fiction', 18),
 ('Soundtrack', 10),
 ('TV Shows', 19),
 ('World', 16)]

In [34]:
%%sql
SELECT
    genre_ID,
    track_id
FROM track

Done.

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 28),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (1, 34),
 (1, 35),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 39),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (1, 50),
 (1, 51),
 (1, 52),
 (1, 53),
 (1, 54),
 (1, 55),
 (1, 56),
 (1, 57),
 (1, 58),
 (1, 59),
 (1, 60),
 (1, 61),
 (1, 62),
 (1, 85),
 (1, 86),
 (1, 87),
 (1, 88),
 (1, 89),
 (1, 90),
 (1, 91),
 (1, 92),
 (1, 93),
 (1, 94),
 (1, 95),
 (1, 96),
 (1, 97),
 (1, 98),
 (1, 337),
 (1, 338),
 (1, 339),
 (1, 340),
 (1, 341),
 (1, 342),
 (1, 343),
 (1, 344),
 (1, 345),
 (1, 346),
 (1, 347),
 (1, 348),
 (1, 349),
 (1, 350),
 (1, 351),
 (1, 352),
 (1, 353),
 (1, 354),
 (1, 355),
 (1, 356),
 (1, 357),
 (1, 358),
 (1, 359),
 (1, 419),
 (1, 420),
 (1, 421),
 (1, 422),
 (1, 423),
 (1, 424),
 (1, 425),
 (1, 426),
 (1, 427),
 (1, 428),
 (1, 429),
 (1, 430),
 (1, 431),
 (1, 432),
 (1, 433),
 (1, 434),
 (1, 435),
 (1, 436),
 (1, 437),
 (1, 438),
 (1, 439),
 (1, 440),
 (1, 441),
 (1, 442),
 (1, 443),
 (1, 444),
 (1, 445),
 (1, 446),
 (1, 447),
 (1, 448),
 (1, 449),
 (1, 450),
 (1, 451),
 (1, 452),
 (1, 453),
 (1, 454),
 (1, 455),
 (1, 489),
 (1, 490),
 (1, 491),
 (1, 492),
 (1, 493),
 (1, 494),
 (1, 495),
 (1, 496),
 (1, 497),
 (1, 498),
 (1, 499),
 (1, 500),
 (1, 543),
 (1, 544),
 (1, 545),
 (1, 546),
 (1, 547),
 (1, 548),
 (1, 549),
 (1, 550),
 (1, 551),
 (1, 552),
 (1, 553),
 (1, 554),
 (1, 555),
 (1, 570),
 (1, 571),
 (1, 572),
 (1, 573),
 (1, 574),
 (1, 575),
 (1, 576),
 (1, 577),
 (1, 578),
 (1, 579),
 (1, 580),
 (1, 581),
 (1, 582),
 (1, 620),
 (1, 621),
 (1, 622),
 (1, 623),
 (1, 675),
 (1, 676),
 (1, 677),
 (1, 678),
 (1, 679),
 (1, 680),
 (1, 681),
 (1, 682),
 (1, 683),
 (1, 684),
 (1, 685),
 (1, 686),
 (1, 687),
 (1, 688),
 (1, 689),
 (1, 690),
 (1, 691),
 (1, 692),
 (1, 693),
 (1, 694),
 (1, 695),
 (1, 696),
 (1, 697),
 (1, 698),
 (1, 699),
 (1, 700),
 (1, 701),
 (1, 702),
 (1, 703),
 (1, 704),
 (1, 705),
 (1, 706),
 (1, 707),
 (1, 708),
 (1, 709),
 (1, 710),
 (1, 711),
 (1, 712),
 (1, 713),
 (1, 714),
 (1, 745),
 (1, 746),
 (1, 747),
 (1, 748),
 (1, 749),
 (1, 750),
 (1, 751),
 (1, 752),
 (1, 753),
 (1, 754),
 (1, 755),
 (1, 756),
 (1, 757),
 (1, 758),
 (1, 759),
 (1, 760),
 (1, 761),
 (1, 762),
 (1, 763),
 (1, 764),
 (1, 765),
 (1, 766),
 (1, 767),
 (1, 768),
 (1, 769),
 (1, 770),
 (1, 771),
 (1, 772),
 (1, 773),
 (1, 774),
 (1, 775),
 (1, 776),
 (1, 777),
 (1, 778),
 (1, 779),
 (1, 780),
 (1, 781),
 (1, 782),
 (1, 783),
 (1, 784),
 (1, 785),
 (1, 786),
 (1, 787),
 (1, 788),
 (1, 789),
 (1, 790),
 (1, 791),
 (1, 792),
 (1, 793),
 (1, 794),
 (1, 795),
 (1, 796),
 (1, 797),
 (1, 798),
 (1, 799),
 (1, 800),
 (1, 801),
 (1, 802),
 (1, 803),
 (1, 804),
 (1, 805),
 (1, 806),
 (1, 807),
 (1, 808),
 (1, 809),
 (1, 810),
 (1, 811),
 (1, 812),
 (1, 813),
 (1, 814),
 (1, 815),
 (1, 816),
 (1, 817),
 (1, 818),
 (1, 819),
 (1, 820),
 (1, 821),
 (1, 822),
 (1, 823),
 (1, 824),
 (1, 825),
 (1, 826),
 (1, 827),
 (1, 828),
 (1, 829),
 (1, 830),
 (1, 831),
 (1, 832),
 (1, 833),
 (1, 834),
 (1, 835),
 (1, 836),
 (1, 837),
 (1, 838),
 (1, 839),
 (1, 840),
 (1, 841),
 (1, 949),
 (1, 950),
 (1, 951),
 (1, 952),
 (1, 953),
 (1, 954),
 (1, 955),
 (1, 956),
 (1, 957),
 (1, 958),
 (1, 959),
 (1, 960),
 (1, 961),
 (1, 962),
 (1, 963),
 (1, 989),
 (1, 990),
 (1, 991),
 (1, 992),
 (1, 993),
 (1, 994),
 (1, 995),
 (1, 996),
 (1, 997),
 (1, 998),
 (1, 999),
 (1, 1000),
 (1, 1001),
 (1, 1002),
 (1, 1003),
 (1, 1004),
 (1, 1005),
 (1, 1006),
 (1, 1007),
 (1, 1008),
 (1, 1020),
 (1, 1021),
 (1, 1022),
 (1, 1023),
 (1, 1024),
 (1, 1025),
 (1, 1026),
 (1, 1027),
 (1, 1028),
 (1, 1029),
 (1, 1030),
 (1, 1031),
 (1, 1032),
 (1, 1146),
 (1, 1147),
 (1, 1148),
 (1, 1149),
 (1, 1150),
 (1, 1151),
 (1, 1152),
 (1, 1153),
 (1, 1154),
 (1, 1155),
 (1, 1156),
 (1, 1157),
 (1, 1158),
 (1, 1159),
 (1, 1160),
 (1, 1161),
 (1, 1162),
 (1, 1163),
 (1, 1164),
 (1, 1165),
 (1, 1166),
 (1, 1167),
 (1, 1168),
 (1, 1169),
 (1, 1170),
 (1, 1171),
 (1, 1172),
 (1, 1173),
 (1, 1201),
 (1, 1202),
 (1, 1203),
 (1, 1204),
 (1, 1205),
 (1, 1206),
 (1, 1207),
 (1, 1208),
 (1, 1209),
 (1, 1210),
 (1, 1211),
 (1, 1235),
 (1, 1236),
 (1, 1237),
 (1, 1238),
 (1, 1239),
 (1, 1240),
 (1, 1241),
 (1, 1242),
 (1, 1243),
 (1, 1244),
 (1, 1256),
 (1, 1257),
 (1, 1258),
 (1, 1259),
 (1, 1260),
 (1, 1261),
 (1, 1262),
 (1, 1263),
 (1, 1264),
 (1, 1265),
 (1, 1266),
 (1, 1267),
 (1, 1305),
 (1, 1306),
 (1, 1307),
 (1, 1308),
 (1, 1309),
 (1, 1310),
 (1, 1311),
 (1, 1312),
 (1, 1313),
 (1, 1314),
 (1, 1315),
 (1, 1316),
 (1, 1317),
 (1, 1318),
 (1, 1319),
 (1, 1320),
 (1, 1321),
 (1, 1322),
 (1, 1323),
 (1, 1324),
 (1, 1362),
 (1, 1363),
 (1, 1365),
 (1, 1366),
 (1, 1367),
 (1, 1368),
 (1, 1369),
 (1, 1370),
 (1, 1393),
 (1, 1395),
 (1, 1396),
 (1, 1397),
 (1, 1398),
 (1, 1399),
 (1, 1400),
 (1, 1401),
 (1, 1402),
 (1, 1403),
 (1, 1404),
 (1, 1405),
 (1, 1406),
 (1, 1407),
 (1, 1408),
 (1, 1409),
 (1, 1410),
 (1, 1411),
 (1, 1412),
 (1, 1413),
 (1, 1434),
 (1, 1435),
 (1, 1436),
 (1, 1437),
 (1, 1438),
 (1, 1439),
 (1, 1440),
 (1, 1441),
 (1, 1442),
 (1, 1443),
 (1, 1479),
 (1, 1480),
 (1, 1481),
 (1, 1482),
 (1, 1483),
 (1, 1484),
 (1, 1485),
 (1, 1486),
 (1, 1487),
 (1, 1488),
 (1, 1489),
 (1, 1490),
 (1, 1491),
 (1, 1492),
 (1, 1493),
 (1, 1494),
 (1, 1495),
 (1, 1496),
 (1, 1497),
 (1, 1498),
 (1, 1499),
 (1, 1500),
 (1, 1501),
 (1, 1502),
 (1, 1503),
 (1, 1504),
 (1, 1505),
 (1, 1562),
 (1, 1563),
 (1, 1564),
 (1, 1565),
 (1, 1566),
 (1, 1567),
 (1, 1568),
 (1, 1569),
 (1, 1570),
 (1, 1571),
 (1, 1572),
 (1, 1573),
 (1, 1574),
 (1, 1575),
 (1, 1576),
 (1, 1577),
 (1, 1578),
 (1, 1579),
 (1, 1580),
 (1, 1581),
 (1, 1582),
 (1, 1583),
 (1, 1584),
 (1, 1585),
 (1, 1586),
 (1, 1587),
 (1, 1588),
 (1, 1589),
 (1, 1590),
 (1, 1591),
 (1, 1592),
 (1, 1593),
 (1, 1594),
 (1, 1595),
 (1, 1596),
 (1, 1597),
 (1, 1598),
 (1, 1599),
 (1, 1600),
 (1, 1601),
 (1, 1602),
 (1, 1603),
 (1, 1604),
 (1, 1605),
 (1, 1606),
 (1, 1607),
 (1, 1608),
 (1, 1609),
 (1, 1610),
 (1, 1611),
 (1, 1612),
 (1, 1613),
 (1, 1614),
 (1, 1615),
 (1, 1616),
 (1, 1617),
 (1, 1618),
 (1, 1619),
 (1, 1620),
 (1, 1621),
 (1, 1622),
 (1, 1623),
 (1, 1624),
 (1, 1625),
 (1, 1626),
 (1, 1627),
 (1, 1628),
 (1, 1629),
 (1, 1630),
 (1, 1631),
 (1, 1632),
 (1, 1633),
 (1, 1634),
 (1, 1635),
 (1, 1636),
 (1, 1637),
 (1, 1638),
 (1, 1639),
 (1, 1640),
 (1, 1641),
 (1, 1642),
 (1, 1643),
 (1, 1644),
 (1, 1645),
 (1, 1646),
 (1, 1647),
 (1, 1648),
 (1, 1649),
 (1, 1650),
 (1, 1651),
 (1, 1652),
 (1, 1653),
 (1, 1654),
 (1, 1655),
 (1, 1656),
 (1, 1657),
 (1, 1658),
 (1, 1659),
 (1, 1660),
 (1, 1661),
 (1, 1662),
 (1, 1663),
 (1, 1664),
 (1, 1665),
 (1, 1666),
 (1, 1667),
 (1, 1668),
 (1, 1669),
 (1, 1670),
 (1, 1702),
 (1, 1703),
 (1, 1704),
 (1, 1705),
 (1, 1706),
 (1, 1707),
 (1, 1708),
 (1, 1709),
 (1, 1710),
 (1, 1711),
 (1, 1712),
 (1, 1713),
 (1, 1714),
 (1, 1715),
 (1, 1716),
 (1, 1745),
 (1, 1746),
 (1, 1747),
 (1, 1748),
 (1, 1749),
 (1, 1750),
 (1, 1751),
 (1, 1752),
 (1, 1753),
 (1, 1754),
 (1, 1791),
 (1, 1792),
 (1, 1793),
 (1, 1794),
 (1, 1795),
 (1, 1796),
 (1, 1797),
 (1, 1798),
 (1, 1799),
 (1, 1800),
 (1, 1986),
 (1, 1987),
 (1, 1988),
 (1, 1989),
 (1, 1990),
 (1, 1991),
 (1, 1992),
 (1, 1993),
 (1, 1994),
 (1, 1995),
 (1, 1996),
 (1, 1997),
 (1, 1998),
 (1, 1999),
 (1, 2000),
 (1, 2001),
 (1, 2002),
 (1, 2003),
 (1, 2004),
 (1, 2005),
 (1, 2006),
 (1, 2007),
 (1, 2008),
 (1, 2009),
 (1, 2010),
 (1, 2011),
 (1, 2012),
 (1, 2013),
 (1, 2014),
 (1, 2015),
 (1, 2016),
 (1, 2017),
 (1, 2018),
 (1, 2019),
 (1, 2020),
 (1, 2021),
 (1, 2022),
 (1, 2023),
 (1, 2024),
 (1, 2025),
 (1, 2026),
 (1, 2027),
 (1, 2028),
 (1, 2029),
 (1, 2093),
 (1, 2094),
 (1, 2095),
 (1, 2096),
 (1, 2097),
 (1, 2098),
 (1, 2113),
 (1, 2114),
 (1, 2115),
 (1, 2116),
 (1, 2117),
 (1, 2118),
 (1, 2119),
 (1, 2120),
 (1, 2121),
 (1, 2122),
 (1, 2123),
 (1, 2124),
 (1, 2139),
 (1, 2140),
 (1, 2141),
 (1, 2142),
 (1, 2143),
 (1, 2144),
 (1, 2145),
 (1, 2146),
 (1, 2147),
 (1, 2148),
 (1, 2149),
 (1, 2150),
 (1, 2151),
 (1, 2152),
 (1, 2153),
 (1, 2154),
 (1, 2155),
 (1, 2156),
 (1, 2157),
 (1, 2158),
 (1, 2159),
 (1, 2160),
 (1, 2161),
 (1, 2162),
 (1, 2163),
 (1, 2164),
 (1, 2178),
 (1, 2179),
 (1, 2180),
 (1, 2181),
 (1, 2182),
 (1, 2183),
 (1, 2184),
 (1, 2185),
 (1, 2186),
 (1, 2187),
 (1, 2188),
 (1, 2189),
 (1, 2190),
 (1, 2191),
 (1, 2192),
 (1, 2193),
 (1, 2194),
 (1, 2195),
 (1, 2196),
 (1, 2197),
 (1, 2198),
 (1, 2199),
 (1, 2200),
 (1, 2201),
 (1, 2202),
 (1, 2203),
 (1, 2204),
 (1, 2205),
 (1, 2206),
 (1, 2207),
 (1, 2208),
 (1, 2209),
 (1, 2210),
 (1, 2211),
 (1, 2212),
 (1, 2213),
 (1, 2214),
 (1, 2215),
 (1, 2229),
 (1, 2230),
 (1, 2231),
 (1, 2232),
 (1, 2233),
 (1, 2234),
 (1, 2235),
 (1, 2236),
 (1, 2237),
 (1, 2254),
 (1, 2255),
 (1, 2256),
 (1, 2257),
 (1, 2258),
 (1, 2259),
 (1, 2260),
 (1, 2261),
 (1, 2262),
 (1, 2263),
 (1, 2264),
 (1, 2265),
 (1, 2266),
 (1, 2267),
 (1, 2268),
 (1, 2269),
 (1, 2270),
 (1, 2271),
 (1, 2272),
 (1, 2273),
 (1, 2274),
 (1, 2275),
 (1, 2276),
 (1, 2277),
 (1, 2278),
 (1, 2279),
 (1, 2280),
 (1, 2281),
 (1, 2296),
 (1, 2297),
 (1, 2298),
 (1, 2299),
 (1, 2300),
 (1, 2301),
 (1, 2302),
 (1, 2303),
 (1, 2304),
 (1, 2305),
 (1, 2306),
 (1, 2307),
 (1, 2308),
 (1, 2309),
 (1, 2344),
 (1, 2345),
 (1, 2346),
 (1, 2347),
 (1, 2348),
 (1, 2349),
 (1, 2350),
 (1, 2351),
 (1, 2352),
 (1, 2353),
 (1, 2354),
 (1, 2355),
 (1, 2356),
 (1, 2357),
 (1, 2375),
 (1, 2376),
 (1, 2377),
 (1, 2378),
 (1, 2379),
 (1, 2380),
 (1, 2381),
 (1, 2382),
 (1, 2383),
 (1, 2384),
 (1, 2385),
 (1, 2386),
 (1, 2387),
 (1, 2388),
 (1, 2389),
 (1, 2390),
 (1, 2391),
 (1, 2392),
 (1, 2393),
 (1, 2394),
 (1, 2395),
 (1, 2396),
 (1, 2397),
 (1, 2398),
 (1, 2399),
 (1, 2400),
 (1, 2401),
 (1, 2402),
 (1, 2403),
 (1, 2404),
 (1, 2405),
 (1, 2406),
 (1, 2407),
 (1, 2408),
 (1, 2409),
 (1, 2410),
 (1, 2411),
 (1, 2412),
 (1, 2413),
 (1, 2414),
 (1, 2415),
 (1, 2416),
 (1, 2417),
 (1, 2418),
 (1, 2419),
 (1, 2420),
 (1, 2421),
 (1, 2422),
 (1, 2423),
 (1, 2424),
 (1, 2425),
 (1, 2426),
 (1, 2427),
 (1, 2428),
 (1, 2429),
 (1, 2430),
 (1, 2431),
 (1, 2432),
 (1, 2433),
 (1, 2434),
 (1, 2435),
 (1, 2436),
 (1, 2437),
 (1, 2438),
 (1, 2439),
 (1, 2440),
 (1, 2441),
 (1, 2442),
 (1, 2443),
 (1, 2444),
 (1, 2445),
 (1, 2446),
 (1, 2447),
 (1, 2448),
 (1, 2449),
 (1, 2450),
 (1, 2451),
 (1, 2452),
 (1, 2453),
 (1, 2454),
 (1, 2455),
 (1, 2456),
 (1, 2457),
 (1, 2458),
 (1, 2459),
 (1, 2460),
 (1, 2461),
 (1, 2462),
 (1, 2463),
 (1, 2464),
 (1, 2465),
 (1, 2466),
 (1, 2467),
 (1, 2468),
 (1, 2469),
 (1, 2470),
 (1, 2471),
 (1, 2506),
 (1, 2507),
 (1, 2508),
 (1, 2509),
 (1, 2510),
 (1, 2511),
 (1, 2512),
 (1, 2513),
 (1, 2514),
 (1, 2515),
 (1, 2516),
 (1, 2517),
 (1, 2518),
 (1, 2519),
 (1, 2520),
 (1, 2521),
 (1, 2522),
 (1, 2542),
 (1, 2543),
 (1, 2544),
 (1, 2545),
 (1, 2546),
 (1, 2547),
 (1, 2548),
 (1, 2549),
 (1, 2550),
 (1, 2551),
 (1, 2552),
 (1, 2553),
 (1, 2565),
 (1, 2566),
 (1, 2567),
 (1, 2568),
 (1, 2569),
 (1, 2570),
 (1, 2571),
 (1, 2609),
 (1, 2610),
 (1, 2611),
 (1, 2612),
 (1, 2613),
 (1, 2614),
 (1, 2615),
 (1, 2616),
 (1, 2617),
 (1, 2618),
 (1, 2619),
 (1, 2620),
 (1, 2621),
 (1, 2622),
 (1, 2623),
 (1, 2624),
 (1, 2625),
 (1, 2626),
 (1, 2627),
 (1, 2628),
 (1, 2629),
 (1, 2630),
 (1, 2631),
 ...]

In [33]:
%%sql
SELECT
    genre_ID,
    COUNT(track_id) counter
FROM track
GROUP BY 1

Done.

[(1, 1297),
 (2, 130),
 (3, 374),
 (4, 332),
 (5, 12),
 (6, 81),
 (7, 579),
 (8, 58),
 (9, 48),
 (10, 43),
 (11, 15),
 (12, 24),
 (13, 28),
 (14, 61),
 (15, 30),
 (16, 28),
 (17, 35),
 (18, 13),
 (19, 93),
 (20, 26),
 (21, 64),
 (22, 17),
 (23, 40),
 (24, 74),
 (25, 1)]

In [84]:
%%sql

WITH
    genre_counts_by_id AS
        (
         SELECT
            genre_id,
            COUNT(track_id) counter
        FROM track
        GROUP BY 1
        )
        

SELECT 
    g.name, 
    gc.counter
FROM genre g
INNER JOIN genre_counts_by_id gc ON gc.genre_id = g.genre_id
GROUP BY 1
ORDER BY 2 DESC;

Done.

[('Rock', 1297),
 ('Latin', 579),
 ('Metal', 374),
 ('Alternative & Punk', 332),
 ('Jazz', 130),
 ('TV Shows', 93),
 ('Blues', 81),
 ('Classical', 74),
 ('Drama', 64),
 ('R&B/Soul', 61),
 ('Reggae', 58),
 ('Pop', 48),
 ('Soundtrack', 43),
 ('Alternative', 40),
 ('Hip Hop/Rap', 35),
 ('Electronica/Dance', 30),
 ('Heavy Metal', 28),
 ('World', 28),
 ('Sci Fi & Fantasy', 26),
 ('Easy Listening', 24),
 ('Comedy', 17),
 ('Bossa Nova', 15),
 ('Science Fiction', 13),
 ('Rock And Roll', 12),
 ('Opera', 1)]

In [85]:
%%sql

WITH usa_tracks_sold AS
   (
    SELECT il.* FROM invoice_line il
    INNER JOIN invoice i on il.invoice_id = i.invoice_id
    INNER JOIN customer c on i.customer_id = c.customer_id
    WHERE c.country = "USA"
   )

SELECT
    g.name genre,
    count(uts.invoice_line_id) tracks_sold,
    cast(count(uts.invoice_line_id) AS FLOAT) / (
        SELECT COUNT(*) from usa_tracks_sold
    ) percentage_sold
FROM usa_tracks_sold uts
INNER JOIN track t on t.track_id = uts.track_id
INNER JOIN genre g on g.genre_id = t.genre_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

Done.

[('Rock', 561, 0.5337773549000951),
 ('Alternative & Punk', 130, 0.12369172216936251),
 ('Metal', 124, 0.11798287345385347),
 ('R&B/Soul', 53, 0.05042816365366318),
 ('Blues', 36, 0.03425309229305423),
 ('Alternative', 35, 0.03330161750713606),
 ('Latin', 22, 0.02093244529019981),
 ('Pop', 22, 0.02093244529019981),
 ('Hip Hop/Rap', 20, 0.019029495718363463),
 ('Jazz', 14, 0.013320647002854425)]

Based on the sales of tracks across different genres in the USA, we should purchase the new albums by the following artists:

    Red Tone (Punk)
    Slim Jim Bites (Blues)
    Meteor and the Girls (Pop)

It's worth keeping in mind that combined, these three genres only make up only 17% of total sales, so we should be on the lookout for artists and albums from the 'rock' genre, which accounts for 53% of sales.

### Analyzing Employee Sales Performance

In [86]:
%%sql

WITH customer_support_rep_sales AS
    (
     SELECT
         i.customer_id,
         c.support_rep_id,
         SUM(i.total) total
     FROM invoice i
     INNER JOIN customer c ON i.customer_id = c.customer_id
     GROUP BY 1,2
    )

SELECT
    e.first_name || " " || e.last_name employee,
    e.hire_date,
    SUM(csrs.total) total_sales
FROM customer_support_rep_sales csrs
INNER JOIN employee e ON e.employee_id = csrs.support_rep_id
GROUP BY 1;

Done.

[('Jane Peacock', '2017-04-01 00:00:00', 1731.5099999999998),
 ('Margaret Park', '2017-05-03 00:00:00', 1584.0000000000002),
 ('Steve Johnson', '2017-10-17 00:00:00', 1393.92)]

### Analyzing Sales by Country

In [87]:
%%sql

WITH country_or_other AS
    (
     SELECT
       CASE
           WHEN (
                 SELECT count(*)
                 FROM customer
                 where country = c.country
                ) = 1 THEN "Other"
           ELSE c.country
       END AS country,
       c.customer_id,
       il.*
     FROM invoice_line il
     INNER JOIN invoice i ON i.invoice_id = il.invoice_id
     INNER JOIN customer c ON c.customer_id = i.customer_id
    )

SELECT
    country,
    customers,
    total_sales,
    average_order,
    customer_lifetime_value
FROM
    (
    SELECT
        country,
        count(distinct customer_id) customers,
        SUM(unit_price) total_sales,
        SUM(unit_price) / count(distinct customer_id) customer_lifetime_value,
        SUM(unit_price) / count(distinct invoice_id) average_order,
        CASE
            WHEN country = "Other" THEN 1
            ELSE 0
        END AS sort
    FROM country_or_other
    GROUP BY country
    ORDER BY sort ASC, total_sales DESC
    );

Done.

[('USA', 13, 1040.490000000008, 7.942671755725252, 80.03769230769292),
 ('Canada', 8, 535.5900000000034, 7.047236842105309, 66.94875000000043),
 ('Brazil', 5, 427.68000000000245, 7.011147540983647, 85.53600000000048),
 ('France', 5, 389.0700000000021, 7.781400000000042, 77.81400000000042),
 ('Germany', 4, 334.6200000000016, 8.161463414634186, 83.6550000000004),
 ('Czech Republic', 2, 273.24000000000103, 9.108000000000034, 136.62000000000052),
 ('United Kingdom', 3, 245.52000000000078, 8.768571428571457, 81.84000000000026),
 ('Portugal', 2, 185.13000000000022, 6.3837931034482835, 92.56500000000011),
 ('India', 2, 183.1500000000002, 8.72142857142858, 91.5750000000001),
 ('Other', 15, 1094.9400000000085, 7.448571428571486, 72.99600000000056)]

### Albums vs Individual Tracks

In [88]:
%%sql

WITH invoice_first_track AS
    (
     SELECT
         il.invoice_id invoice_id,
         MIN(il.track_id) first_track_id
     FROM invoice_line il
     GROUP BY 1
    )

SELECT
    album_purchase,
    COUNT(invoice_id) number_of_invoices,
    CAST(count(invoice_id) AS FLOAT) / (
                                         SELECT COUNT(*) FROM invoice
                                      ) percent
FROM
    (
    SELECT
        ifs.*,
        CASE
            WHEN
                 (
                  SELECT t.track_id FROM track t
                  WHERE t.album_id = (
                                      SELECT t2.album_id FROM track t2
                                      WHERE t2.track_id = ifs.first_track_id
                                     ) 

                  EXCEPT 

                  SELECT il2.track_id FROM invoice_line il2
                  WHERE il2.invoice_id = ifs.invoice_id
                 ) IS NULL
             AND
                 (
                  SELECT il2.track_id FROM invoice_line il2
                  WHERE il2.invoice_id = ifs.invoice_id

                  EXCEPT 

                  SELECT t.track_id FROM track t
                  WHERE t.album_id = (
                                      SELECT t2.album_id FROM track t2
                                      WHERE t2.track_id = ifs.first_track_id
                                     ) 
                 ) IS NULL
             THEN "yes"
             ELSE "no"
         END AS "album_purchase"
     FROM invoice_first_track ifs
    )
GROUP BY album_purchase;

Done.

[('no', 500, 0.8143322475570033), ('yes', 114, 0.18566775244299674)]